
   
name: Automatic build

on:
  push:
    branches: [ stable ]

env:
  NODE_VERSION: "14"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUBLIC_PAT_CICD4 }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm install
      - name: Build files
        run: |
          npm run build
      - name: Commit and push
        run: |
          git config user.name "plenty-cicd-4"
          git config user.email "98583752+plenty-cicd-4@users.noreply.github.com"
          git add --force resources/js/dist/plentyshop-lts-modern.js
          git add --force resources/js/dist/plentyshop-lts-modern.js.map
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic build" && git push origin HEAD:stable
